channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.3
  - seaborn==0.13.2
  - pickle4==0.0.1
  - bokeh==3.5.2
  - mlflow==2.16
  - scikit-learn==1.5.2
name: mlflow-env
